### ISSUE TITLE
settings not saved error

### ISSUE THREAD

**Issue by critzo** [throneless-tech/piecewise-saas#15]
I'm not sure what the issue is, perhaps the logs can tell us. When saving site settings for demo2, I get the error below:
![image](https://user-images.githubusercontent.com/4633345/92611954-5479da00-f287-11ea-9e63-5f56cb054058.png)

This appears to be related to the Thank You Message field, or at least I suspect that. All other settings I added were saved.

**Comment by critzo** [comment]
Correction. Though the settings appear to be saved in the admin interface, the front page of the survey is not updated.

**Comment by jheretic** [comment]
Ah, good catch. Looks like there's a slight discrepancy between what the backend considers required and what the frontend does. Should be a quick fix.
