### ISSUE TITLE
need second role for non-admins

### ISSUE THREAD

**Issue by critzo** [throneless-tech/piecewise-saas#27]
When setting up a new instance, I added a new user intending to only provide them access to that instance. However, the user add form only provides one role-- Admins-- and if you try submitting a user without selecting that role, an error occurs. Adding the user with the admins role gives that user access to the saas service, so an additional role is needed for instance-only admins.

**Comment by jheretic** [comment]
That was an oversight in that the production database seeds only included the admin group. I added them in c9034c99c436aca32bba89fa1dce953b8be605b7 and updated the database in piecewise.measurementlab.net to match.
