### ISSUE TITLE
Unwanted conflation of groups and roles across SaaS and Piecewise

### ISSUE THREAD

**Issue by jheretic** [throneless-tech/piecewise-saas#6]
Currently there is some conflation of groups and roles across the dashboard and instances. The desired functionality is that:
* A user has a role which is entirely local to that user, and is only utilized by Piecewise instances. That role is either 'admin' or 'viewer'.
* Separately, one or more users has access to login and administer the dashboard.
* Never the twain shall meet.

**Comment by rudietuesdays** [comment]
- needs backend code to be built
- can reuse front end code to hide tabs from `viewer` branch
- users can ONLY log into instance they're associated with
